// Synthetic (made-up) patients whose numbers follow published data instead of hand-typed arrays.
// Everything is generated by a seeded random generator, so the demo is repeatable.
//
// SOURCES (each record was opened and read on 2026-10-04):
//  [1] ClinicalTrials.gov NCT03758755, "The Effect of Blood Flow Restriction Therapy Following ACL Reconstruction", results posted 2022-12-22.
//      n=45 (BPTB, hamstring, quadriceps autografts and allograft). A physical therapist measured the operated knee. Dispersion type is the
//      STANDARD ERROR, so the between-patient SD below is SE x sqrt(n). Standard-rehab arm n=20, blood-flow-restriction arm n=25.
//      Flexion (deg): standard 70.0 / 91.75 / 112.74 / 130.50 and BFR 76.4 / 102.02 / 121.08 / 137.18 at 2 / 4 / 6 / 12 weeks.
//      Pain VAS 0-10 (standard arm): 3.18 pre-op, 3.16 / 1.51 / 1.16 at 2 / 6 / 12 weeks.
//  [2] Hyperextension graft-fixation RCT, J Orthop Traumatol 2016 (PMC5071236), n=98, goniometer: loss of extension in the control group was
//      0-3 deg in 56% at 2 weeks and 80% at 6 weeks, 4-5 deg in 38% and 16%, 6-10 deg in 2% and 4%.
//  [3] Chew et al., PLOS ONE 2024 (PMC11449355), n=30, phone self-measurement: repeat readings differ by 2.0 deg (flexion) and 0.9 deg (extension)
//      on average; against a goniometer 4.5 and 2.2 deg; minimal detectable change 5.3 and 3.1 deg.
//  [4] Shrivastava et al., Wellcome Open Research 2025: test-retest limits of agreement +-8.5 deg (flexion) and +-6.5 deg (extension),
//      i.e. one reading has an SD of about 8.5/1.96/sqrt(2) = 3.1 deg and 6.5/1.96/sqrt(2) = 2.3 deg.
//
// ASSUMPTIONS (not from a source): flexion about 50 deg (standard) and 56 deg (BFR) on post-op day 3; the day-to-day SD of the true values
// (2 deg flexion, 1 deg extension, 1.1 pain points); the shape of the extension-deficit decay; and the flare-up pattern of the stiff patient.

export type Pt = [day: number, value: number];

export const FLEX_STANDARD: Pt[] = [[3, 50], [14, 70.0], [28, 91.75], [42, 112.74], [84, 130.5]];
export const FLEX_FAST: Pt[] = [[3, 56], [14, 76.4], [28, 102.02], [42, 121.08], [84, 137.18]];
// Between-patient SD of flexion = standard error x sqrt(n) from [1]
export const FLEX_SD_STANDARD: Pt[] = [[14, 5.35 * Math.sqrt(20)], [28, 4.18 * Math.sqrt(20)], [42, 3.74 * Math.sqrt(20)], [84, 2.59 * Math.sqrt(20)]];
export const FLEX_SD_FAST: Pt[] = [[14, 3.53 * 5], [28, 3.07 * 5], [42, 2.73 * 5], [84, 2.2 * 5]];
export const PAIN_STANDARD: Pt[] = [[0, 3.18], [14, 3.16], [42, 1.51], [84, 1.16]];

// Measurement noise of ONE phone reading [4], plus assumed true day-to-day variation
export const FLEX_READING_SD = 8.5 / 1.96 / Math.SQRT2, EXT_READING_SD = 6.5 / 1.96 / Math.SQRT2;
const FLEX_DAILY_SD = Math.hypot(FLEX_READING_SD, 2), EXT_DAILY_SD = Math.hypot(EXT_READING_SD, 1), PAIN_DAILY_SD = 1.1;

export function interp(pts: Pt[], x: number): number {
  if (x <= pts[0][0]) return pts[0][1];
  for (let i = 1; i < pts.length; i++) if (x <= pts[i][0]) { const [x0, y0] = pts[i - 1], [x1, y1] = pts[i]; return y0 + ((y1 - y0) * (x - x0)) / (x1 - x0); }
  return pts[pts.length - 1][1];
}
export function mulberry32(seed: number) { let a = seed >>> 0; return () => { a = (a + 0x6d2b79f5) >>> 0; let t = a; t = Math.imul(t ^ (t >>> 15), t | 1); t ^= t + Math.imul(t ^ (t >>> 7), t | 61); return ((t ^ (t >>> 14)) >>> 0) / 4294967296; }; }
export function gauss(rng: () => number): number { let u = 0, v = 0; while (u === 0) u = rng(); while (v === 0) v = rng(); return Math.sqrt(-2 * Math.log(u)) * Math.cos(2 * Math.PI * v); }

export interface Archetype {
  curve: 'standard' | 'fast';
  /** Where this patient sits in the between-patient spread (0 = average, +1 = one SD better than average). */
  z: number;
  /** True extension deficit (deg): starts at `start` on post-op day 6 and decays to `end` (time constant 7 days). */
  ext: { start: number; end: number };
  painOffset: number;
  /** A setback (swelling, stiffness) from post-op day `from`. */
  flare?: { from: number; pain: number; flexion: number; ext: number };
  seed: number;
}

export interface DayReading { day: number; flexion: number; extension: number; pain: number }

export function simulate(a: Archetype, fromDay: number, toDay: number): DayReading[] {
  const rng = mulberry32(a.seed), mean = a.curve === 'fast' ? FLEX_FAST : FLEX_STANDARD, sd = a.curve === 'fast' ? FLEX_SD_FAST : FLEX_SD_STANDARD, out: DayReading[] = [];
  for (let day = fromDay; day <= toDay; day++) {
    const fl = a.flare && day >= a.flare.from ? a.flare : undefined;
    const flex = interp(mean, day) + a.z * interp(sd, day) + (fl?.flexion ?? 0) + gauss(rng) * FLEX_DAILY_SD;
    const trueExt = a.ext.end + (a.ext.start - a.ext.end) * Math.exp(-(day - 6) / 7) + (fl?.ext ?? 0);
    const ext = Math.max(0, trueExt + gauss(rng) * EXT_DAILY_SD);          // the phone measures the size of the angle, never below 0
    const pain = interp(PAIN_STANDARD, day) + a.painOffset + (fl?.pain ?? 0) + gauss(rng) * PAIN_DAILY_SD;
    out.push({ day, flexion: Math.round(Math.min(150, Math.max(30, flex))), extension: Math.round(Math.min(40, ext)), pain: Math.round(Math.min(10, Math.max(0, pain))) });
  }
  return out;
}

/** Healthy other knee (reference reading): normal knee flexion is about 135-140 deg and extension about 0 (general anatomy, not from the sources above). */
export const referenceReading = () => ({ flexion: 138, extension: 0, pain: 0 });

export const ARCHETYPES: Record<string, Archetype> = {
  // average-to-good recovery, standard rehab curve
  'P-7F3A': { curve: 'standard', z: 0.5, ext: { start: 3.5, end: 0.8 }, painOffset: -0.4, seed: 6 },
  // setback: swelling and stiffness appear on post-op day 13 (pain up, flexion down, extension deficit up)
  'P-2C91': { curve: 'standard', z: 0.1, ext: { start: 4, end: 1.5 }, painOffset: 0.2, flare: { from: 13, pain: 3.8, flexion: -14, ext: 6 }, seed: 5 },
  // fast recovery (the blood-flow-restriction arm of [1] is the faster published curve)
  'P-B804': { curve: 'fast', z: 0.9, ext: { start: 2.5, end: 0.3 }, painOffset: -0.8, seed: 5 },
};
